### ISSUE TITLE
3KH0 ISSUE; PLEASE REPLY!

### ISSUE THREAD

**Issue by TheGlitchedPhoenix** [Cognition-Dev/discussion#3]
I recently got a notification that Cyclic was approved. I looked around and found the page for Cognition-dev.github.io.
We could be taken down for having the word 3kho on our site. We need to fix this because if someone goes to this site then it'll be sent to the universal Blocklist (and yes I've seen it).

Please reply soon,

PhoenixOnFire.

**Comment by OMEGA6405** [comment]
@TheGlitchedPhoenix if it gets bloced we change domais
